// Centralized labels for the quickfilter plugin

// List of all accepted languages in the system - only those defined in PLUGIN_LABELS
export const acceptedLanguages = ['ar', 'en', 'es', 'fr', 'he', 'zh'];

export const PLUGIN_LABELS = {
  en: {
    quickFilters: 'Quick Filters',
    clearFilters: 'Clear Filters',
    activeFilterSingular: 'Active filter on column',
    activeFilterPlural: 'Active filters on columns',
    custom: 'Custom',
    all: 'All',
    yes: 'Yes',
    no: 'No',
    selectOption: 'Select Option',
    from: 'From',
    to: 'To',
    selectDate: 'Select Date',
    past: 'Past',
    future: 'Future',
    presentFuture: 'Present & Future',
    customRange: 'Custom Range',
    apply: 'Apply',
    cancel: 'Cancel',
    yesterday: 'Yesterday',
    lastWeek: 'Last Week',
    lastMonth: 'Last Month',
    last7Days: 'Last 7 Days',
    last30Days: 'Last 30 Days',
    lastYear: 'Last Year',
    last2Years: 'Last 2 Years',
    allPast: 'All Past',
    today: 'Today',
    thisWeek: 'This Week',
    thisMonth: 'This Month',
    next7Days: 'Next 7 Days',
    next30Days: 'Next 30 Days',
    todayAndFuture: 'Today & Future',
    allFuture: 'All Future',
  },
  ar: {
    quickFilters: 'فلاتر سريعة',
    clearFilters: 'مسح الفلاتر',
    activeFilterSingular: 'فلتر نشط على العمود',
    activeFilterPlural: 'فلاتر نشطة على الأعمدة',
    custom: 'مخصص',
    all: 'الكل',
    yes: 'نعم',
    no: 'لا',
    selectOption: 'اختر خيارًا',
    from: 'من',
    to: 'إلى',
    selectDate: 'اختر التاريخ',
    past: 'الماضي',
    future: 'المستقبل',
    presentFuture: 'الحاضر والمستقبل',
    customRange: 'نطاق مخصص',
    apply: 'تطبيق',
    cancel: 'إلغاء',
    yesterday: 'أمس',
    lastWeek: 'الأسبوع الماضي',
    lastMonth: 'الشهر الماضي',
    last7Days: 'آخر 7 أيام',
    last30Days: 'آخر 30 يومًا',
    lastYear: 'العام الماضي',
    last2Years: 'العامين الماضيين',
    allPast: 'كل الماضي',
    today: 'اليوم',
    thisWeek: 'هذا الأسبوع',
    thisMonth: 'هذا الشهر',
    next7Days: 'الـ 7 أيام القادمة',
    next30Days: 'الـ 30 يومًا القادمة',
    todayAndFuture: 'اليوم والمستقبل',
    allFuture: 'كل المستقبل',
  },
  fr: {
    quickFilters: 'Filtres rapides',
    clearFilters: 'Effacer les filtres',
    activeFilterSingular: 'Filtre actif sur la colonne',
    activeFilterPlural: 'Filtres actifs sur les colonnes',
    custom: 'Personnalisé',
    all: 'Tous',
    yes: 'Oui',
    no: 'Non',
    selectOption: 'Sélectionner une option',
    from: 'De',
    to: 'À',
    selectDate: 'Sélectionner une date',
    past: 'Passé',
    future: 'Futur',
    presentFuture: 'Présent & Futur',
    customRange: 'Plage personnalisée',
    apply: 'Appliquer',
    cancel: 'Annuler',
    yesterday: 'Hier',
    lastWeek: 'Semaine dernière',
    lastMonth: 'Mois dernier',
    last7Days: '7 derniers jours',
    last30Days: '30 derniers jours',
    lastYear: 'Année dernière',
    last2Years: '2 dernières années',
    allPast: 'Tout le passé',
    today: "Aujourd'hui",
    thisWeek: 'Cette semaine',
    thisMonth: 'Ce mois',
    next7Days: '7 prochains jours',
    next30Days: '30 prochains jours',
    todayAndFuture: "Aujourd'hui & Futur",
    allFuture: 'Tout le futur',
  },
  es: {
    quickFilters: 'Filtros rápidos',
    clearFilters: 'Borrar filtros',
    activeFilterSingular: 'Filtro activo en la columna',
    activeFilterPlural: 'Filtros activos en las columnas',
    custom: 'Personalizado',
    all: 'Todos',
    yes: 'Sí',
    no: 'No',
    selectOption: 'Seleccionar opción',
    from: 'Desde',
    to: 'Hasta',
    selectDate: 'Seleccionar fecha',
    past: 'Pasado',
    future: 'Futuro',
    presentFuture: 'Presente & Futuro',
    customRange: 'Rango personalizado',
    apply: 'Aplicar',
    cancel: 'Cancelar',
    yesterday: 'Ayer',
    lastWeek: 'Semana pasada',
    lastMonth: 'Mes pasado',
    last7Days: 'Últimos 7 días',
    last30Days: 'Últimos 30 días',
    lastYear: 'Último año',
    last2Years: 'Últimos 2 años',
    allPast: 'Todo el pasado',
    today: 'Hoy',
    thisWeek: 'Esta semana',
    thisMonth: 'Este mes',
    next7Days: 'Próximos 7 días',
    next30Days: 'Próximos 30 días',
    todayAndFuture: 'Hoy y futuro',
    allFuture: 'Todo el futuro',
  },
  zh: {
    quickFilters: '快速筛选',
    clearFilters: '清除筛选',
    activeFilterSingular: '列上激活的筛选',
    activeFilterPlural: '多列上激活的筛选',
    custom: '自定义',
    all: '全部',
    yes: '是',
    no: '否',
    selectOption: '选择选项',
    from: '从',
    to: '到',
    selectDate: '选择日期',
    past: '过去',
    future: '未来',
    presentFuture: '现在和未来',
    customRange: '自定义范围',
    apply: '应用',
    cancel: '取消',
    yesterday: '昨天',
    lastWeek: '上周',
    lastMonth: '上个月',
    last7Days: '过去7天',
    last30Days: '过去30天',
    lastYear: '去年',
    last2Years: '过去2年',
    allPast: '所有过去',
    today: '今天',
    thisWeek: '本周',
    thisMonth: '本月',
    next7Days: '未来7天',
    next30Days: '未来30天',
    todayAndFuture: '今天和未来',
    allFuture: '所有未来',
  },
  he: {
    quickFilters: 'סינון מהיר',
    clearFilters: 'נקה סינון',
    activeFilterSingular: 'סינון פעיל בעמודה',
    activeFilterPlural: 'סינון פעיל בעמודות',
    custom: 'מותאם אישית',
    all: 'הכל',
    yes: 'כן',
    no: 'לא',
    selectOption: 'בחר אפשרות',
    from: 'מתאריך',
    to: 'עד תאריך',
    selectDate: 'בחר תאריך',
    past: 'עבר',
    future: 'עתיד',
    presentFuture: 'הווה ועתיד',
    customRange: 'טווח מותאם אישית',
    apply: 'החל',
    cancel: 'ביטול',
    yesterday: 'אתמול',
    lastWeek: 'שבוע שעבר',
    lastMonth: 'חודש שעבר',
    last7Days: '7 ימים אחרונים',
    last30Days: '30 ימים אחרונים',
    lastYear: 'שנה שעברה',
    last2Years: 'שנתיים אחרונות',
    allPast: 'בעבר',
    today: 'היום',
    thisWeek: 'השבוע',
    thisMonth: 'החודש',
    next7Days: '7 ימים הבאים',
    next30Days: '30 ימים הבאים',
    todayAndFuture: 'היום והעתיד',
    allFuture: 'בעתיד',
  },
  // Placeholder for other languages (az, bg, bn-BD, etc.)
  // These can be structured similarly with proper translations
} as const;
export type SupportedLocale = keyof typeof PLUGIN_LABELS;
export type LabelKey = keyof typeof PLUGIN_LABELS.en;

// Helper function to get labels for a specific locale
export const getLabels = (locale: SupportedLocale = 'en') => {
  return PLUGIN_LABELS[locale] || PLUGIN_LABELS.en;
};

// Helper function to get a specific label
export const getLabel = (key: LabelKey, locale: SupportedLocale = 'en'): string => {
  const labels = getLabels(locale);
  const value = labels[key as keyof typeof labels];

  if (typeof value === 'string') {
    return value;
  }

  // Fallback to English if not found
  const fallbackLabels = getLabels('en');
  const fallbackValue = fallbackLabels[key];

  return typeof fallbackValue === 'string' ? fallbackValue : String(key);
};
